let pageinfo={shirt:{heading:"MEN'S SHIRTS",body:"Quality fabrics and modern fits are key when it comes to refined essentials. Good news: our stylish men's shirts offer both. Complete your tailored looks with plain or patterned non-iron styles that impress in the boardroom. When the golf club beckons, opt for breathable Polos, crafted with our Tyrwhitt Cool finish.",topbanner:"https://www.charlestyrwhitt.com/on/demandware.static/-/Library-Sites-CTShirtsSharedLibrary/default/dw85c7465f/merchAssets/SS23/TIBs/tib-ss23-053.jpg",
filter:[{'SHIRT FIT':['CLASSICE FIT','SLIM FIT','EXTRA SLIM FIT']},{'COLOR':['OCEAN BLUE','BLUE','CORNFLOWER BLUE','CREAM','LIGHT GREEN','INDIGO BLUE','ORANGE','NAVY','IVORY','WHITE']},{'NON-IRON':['YES','NO']},{'SHIRT COLLAR':['POLO COLLAR','BUTTON-DOWN','SPREAD','CLASSIC','CREW NECK','COLARLESS']}]},
suit:{heading:"MEN'S SUITS",body:"Our suits are all about expert tailoring. We have smart and comfortable business suits for men, crafted from soft wool. Browse understated plain options or embrace bold style with standout checks. For special occasions, classic morning suits that combine tail coats with flat-fronted pants will have you looking the part.",topbanner:'https://www.charlestyrwhitt.com/on/demandware.static/-/Library-Sites-CTShirtsSharedLibrary/default/dw6a0b5d45/merchAssets/SS23/TIBs/tib-ss23-055.jpg',filter:[{'SUIT FIT':['CLASSICE FIT','SLIM FIT','EXTRA SLIM FIT']},{'COLOR':['BLACK','BLUE','BROWN','CREAM','GREEN','GREY','ORANGE','PINK','RED']},{'PATTERN':['CHECK','PLAIN','STRIPE','WOOL']}]},
pant:{heading:"MEN'S PANTS",body:"Comfortable fabrics and flattering fits? Expect both from our formal and casual men's pants. Our chinos are bestsellers for good reason – they feature non-iron finishes, super-soft textures, and slight stretch for comfort. To complete business looks, choose 5-pocket men's smart pants in versatile shades of charcoal, navy, and mocha.",topbanner:'https://www.charlestyrwhitt.com/on/demandware.static/-/Library-Sites-CTShirtsSharedLibrary/default/dw850c72d7/merchAssets/SS23/TIBs/tib-ss23-056.jpg',filter:[{'PANT FIT':['CLASSICE FIT','SLIM FIT','EXTRA SLIM FIT']},{'COLOR':['BLACK','BLUE','BROWN','CREAM','GREEN','GREY','ORANGE','PINK','RED']},{'NON-IRON':['YES','NO']},{'FABRIC':['100% LINEN','100% WOOL','COTTON MIX','LINEN MIX']}]},
shoe:{heading:"MEN'S SHOES",body:"Smart footwear completes an outfit, which is why we've crafted our men's shoes with superior materials. Think lace-up Oxfords and brogues in premium leather or supple suede. As durability is key, our Goodyear-welted soles are constructed to last. When it comes to casual outfits, turn to lightweight sneakers or chunky boots.",topbanner:'https://www.charlestyrwhitt.com/on/demandware.static/-/Library-Sites-CTShirtsSharedLibrary/default/dw72e25c88/merchAssets/SS23/TIBs/tib-ss23-043.jpg',filter:[{'FIT':['REGULAR FIT']},{'COLOR':['BLACK','BLUE','BROWN','CREAM','GREEN','GREY','RED']},{'SHOE STYLE':['SMART','CASUAL','SNEAKER','OXFORD','BOTTS','LOAFER']}]},
product:{heading:"",body:"",topbanner:"",
filter:[{'CATEGORIES':['SHIRT','PANTS','ACCESSORIES','SUITS']}]}}


export default pageinfo;